substitutions:
  _BASE_IMAGE: us-central1-docker.pkg.dev/${PROJECT_ID}/mizzou-crawler/base:latest
  _REGISTRY: us-central1-docker.pkg.dev/${PROJECT_ID}/mizzou-crawler
  _RELEASE_VERSION: '1.3.1'

steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--build-arg'
      - 'BASE_IMAGE=${_BASE_IMAGE}'
      - '-f'
      - 'Dockerfile.crawler'
      - '-t'
      - '${_REGISTRY}/crawler:${SHORT_SHA}'
      - '-t'
      - '${_REGISTRY}/crawler:latest'
      - '-t'
      - '${_REGISTRY}/crawler:v${_RELEASE_VERSION}'
      - '.'
images:
  - '${_REGISTRY}/crawler:${SHORT_SHA}'
  - '${_REGISTRY}/crawler:v${_RELEASE_VERSION}'
  - '${_REGISTRY}/crawler:latest'
timeout: 1800s
options:
  machineType: 'N1_HIGHCPU_8'
  diskSizeGb: 100
  logging: CLOUD_LOGGING_ONLY
