# Cloud Build configuration for building ONLY the processor service
# Usage: gcloud builds submit --config=cloudbuild-processor-only.yaml

steps:
  # Build Processor
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-processor'
    args:
      - 'build'
      - '-t'
      - 'us-central1-docker.pkg.dev/${PROJECT_ID}/mizzou-news-crawler/processor:${SHORT_SHA}'
      - '-t'
      - 'us-central1-docker.pkg.dev/${PROJECT_ID}/mizzou-news-crawler/processor:latest'
      - '-f'
      - 'Dockerfile.processor'
      - '.'

  # Push Processor
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-processor'
    args:
      - 'push'
      - '--all-tags'
      - 'us-central1-docker.pkg.dev/${PROJECT_ID}/mizzou-news-crawler/processor'
    waitFor: ['build-processor']

options:
  machineType: 'N1_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY

timeout: '900s'  # 15 minutes
