# Cloud Build configuration for building all services
# This builds Docker images and pushes to Artifact Registry
# Cloud Deploy handles the actual deployment to GKE

steps:
  # Build Processor
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-processor'
    args:
      - 'build'
      - '-t'
      - 'us-central1-docker.pkg.dev/${PROJECT_ID}/mizzou-news-crawler/processor:${SHORT_SHA}'
      - '-t'
      - 'us-central1-docker.pkg.dev/${PROJECT_ID}/mizzou-news-crawler/processor:latest'
      - '-f'
      - 'Dockerfile.processor'
      - '.'

  # Build API
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-api'
    args:
      - 'build'
      - '-t'
      - 'us-central1-docker.pkg.dev/${PROJECT_ID}/mizzou-news-crawler/api:${SHORT_SHA}'
      - '-t'
      - 'us-central1-docker.pkg.dev/${PROJECT_ID}/mizzou-news-crawler/api:latest'
      - '-f'
      - 'Dockerfile.api'
      - '.'

  # Build Crawler
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-crawler'
    args:
      - 'build'
      - '-t'
      - 'us-central1-docker.pkg.dev/${PROJECT_ID}/mizzou-news-crawler/crawler:${SHORT_SHA}'
      - '-t'
      - 'us-central1-docker.pkg.dev/${PROJECT_ID}/mizzou-news-crawler/crawler:latest'
      - '-f'
      - 'Dockerfile.crawler'
      - '.'

  # Push all images
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-processor'
    args:
      - 'push'
      - '--all-tags'
      - 'us-central1-docker.pkg.dev/${PROJECT_ID}/mizzou-news-crawler/processor'
    waitFor: ['build-processor']

  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-api'
    args:
      - 'push'
      - '--all-tags'
      - 'us-central1-docker.pkg.dev/${PROJECT_ID}/mizzou-news-crawler/api'
    waitFor: ['build-api']

  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-crawler'
    args:
      - 'push'
      - '--all-tags'
      - 'us-central1-docker.pkg.dev/${PROJECT_ID}/mizzou-news-crawler/crawler'
    waitFor: ['build-crawler']

  # Create Cloud Deploy release (only on main branch)
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'create-release'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        if [ "${BRANCH_NAME}" = "main" ]; then
          gcloud deploy releases create release-${SHORT_SHA} \
            --delivery-pipeline=mizzou-news-crawler \
            --region=us-central1 \
            --annotations=commitId=${REVISION_ID} \
            --images=processor=us-central1-docker.pkg.dev/${PROJECT_ID}/mizzou-news-crawler/processor:${SHORT_SHA},api=us-central1-docker.pkg.dev/${PROJECT_ID}/mizzou-news-crawler/api:${SHORT_SHA},crawler=us-central1-docker.pkg.dev/${PROJECT_ID}/mizzou-news-crawler/crawler:${SHORT_SHA}
          echo "✅ Created release for automatic deployment to production"
        else
          echo "ℹ️  Skipping Cloud Deploy release - not on main branch"
          echo "   To manually deploy this build:"
          echo "   gcloud deploy releases create release-${SHORT_SHA} --delivery-pipeline=mizzou-news-crawler --region=us-central1 --images=processor=us-central1-docker.pkg.dev/${PROJECT_ID}/mizzou-news-crawler/processor:${SHORT_SHA},api=us-central1-docker.pkg.dev/${PROJECT_ID}/mizzou-news-crawler/api:${SHORT_SHA},crawler=us-central1-docker.pkg.dev/${PROJECT_ID}/mizzou-news-crawler/crawler:${SHORT_SHA}"
        fi
    waitFor: ['push-processor', 'push-api', 'push-crawler']

options:
  machineType: 'N1_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY

timeout: '1800s'  # 30 minutes
