# Cloud Build configuration for building ONLY the API service
# Usage: gcloud builds submit --config=cloudbuild-api-only.yaml
# Note: Uses shared base image from Artifact Registry

substitutions:
  _BASE_IMAGE: us-central1-docker.pkg.dev/${PROJECT_ID}/mizzou-crawler/base:latest
  _REGISTRY: us-central1-docker.pkg.dev/${PROJECT_ID}/mizzou-crawler
  _RELEASE_VERSION: '1.3.1'

steps:
  # Build API (using shared base image)
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-api'
    args:
      - 'build'
      - '--build-arg'
      - 'BASE_IMAGE=${_BASE_IMAGE}'
      - '-t'
      - '${_REGISTRY}/api:${SHORT_SHA}'
      - '-t'
      - '${_REGISTRY}/api:latest'
      - '-t'
      - '${_REGISTRY}/api:v${_RELEASE_VERSION}'
      - '-f'
      - 'Dockerfile.api'
      - '.'

  # Push API
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-api'
    args:
      - 'push'
      - '--all-tags'
      - '${_REGISTRY}/api'
    waitFor: ['build-api']

options:
  machineType: 'N1_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY

timeout: '300s'  # 5 minutes (reduced from 15 due to base image optimization)
