# Cloud Build configuration for Unified Image Strategy
# Builds a single image for all services (API, Crawler, Processor)

steps:
  # 1. Build the Unified Image
  # This single step replaces the separate builds for base, ml-base, crawler, processor, api
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-unified'
    args:
      - 'build'
      - '-t'
      - 'us-central1-docker.pkg.dev/${PROJECT_ID}/mizzou-news-crawler/unified:${SHORT_SHA}'
      - '-t'
      - 'us-central1-docker.pkg.dev/${PROJECT_ID}/mizzou-news-crawler/unified:latest'
      - '-f'
      - 'Dockerfile.unified'
      - '.'

  # 2. Push the Unified Image
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-unified'
    args:
      - 'push'
      - '--all-tags'
      - 'us-central1-docker.pkg.dev/${PROJECT_ID}/mizzou-news-crawler/unified'
    waitFor: ['build-unified']

  # 3. Run Migrations (using the unified image!)
  # We can use the same image for migrations since it has the code + alembic
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'run-migrations'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        if [ "${BRANCH_NAME}" = "main" ]; then
          echo "🔄 Running database migrations..."
          
          # Get GKE credentials
          gcloud container clusters get-credentials mizzou-cluster \
            --zone=us-central1-a \
            --project=${PROJECT_ID}
          
          # Create migration job using the UNIFIED image
          cat > /tmp/migration-job.yaml <<EOF
        apiVersion: batch/v1
        kind: Job
        metadata:
          name: migration-${SHORT_SHA}
          namespace: production
        spec:
          template:
            spec:
              serviceAccountName: mizzou-app
              restartPolicy: Never
              containers:
              - name: migrator
                image: us-central1-docker.pkg.dev/${PROJECT_ID}/mizzou-news-crawler/unified:${SHORT_SHA}
                command: ["/app/entrypoint.sh", "migrator"]
                env:
                - name: DATABASE_ENGINE
                  value: "postgresql+psycopg2"
                # ... (other env vars same as before) ...
        EOF
          # (Apply logic omitted for brevity, same as original)
        fi
    waitFor: ['push-unified']

  # 4. Create Cloud Deploy Release
  # We deploy the SAME image for all targets
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'create-release'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        if [ "${BRANCH_NAME}" = "main" ]; then
          IMAGE_URL="us-central1-docker.pkg.dev/${PROJECT_ID}/mizzou-news-crawler/unified:${SHORT_SHA}"
          
          gcloud deploy releases create release-${SHORT_SHA} \
            --delivery-pipeline=mizzou-news-crawler \
            --region=us-central1 \
            --annotations=commitId=${REVISION_ID} \
            --images=processor=${IMAGE_URL},api=${IMAGE_URL},crawler=${IMAGE_URL}
            
          echo "✅ Created release using unified image: ${IMAGE_URL}"
        fi
    waitFor: ['push-unified']

options:
  machineType: 'N1_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY
  timeout: '1800s'
