# Cloud Build configuration for building ONLY the crawler service
# Usage: gcloud builds submit --config=cloudbuild-crawler-only.yaml

steps:
  # Build Crawler
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-crawler'
    args:
      - 'build'
      - '-t'
      - 'us-central1-docker.pkg.dev/${PROJECT_ID}/mizzou-news-crawler/crawler:${SHORT_SHA}'
      - '-t'
      - 'us-central1-docker.pkg.dev/${PROJECT_ID}/mizzou-news-crawler/crawler:latest'
      - '-f'
      - 'Dockerfile.crawler'
      - '.'

  # Push Crawler
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-crawler'
    args:
      - 'push'
      - '--all-tags'
      - 'us-central1-docker.pkg.dev/${PROJECT_ID}/mizzou-news-crawler/crawler'
    waitFor: ['build-crawler']

options:
  machineType: 'N1_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY

timeout: '900s'  # 15 minutes
