# Cloud Deploy delivery pipeline configuration
# Defines the deployment pipeline and target environment

apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
  name: mizzou-news-crawler
description: Mizzou News Crawler deployment pipeline
serialPipeline:
  stages:
    - targetId: production
      profiles: [production]
---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: production
description: Production GKE cluster
gke:
  cluster: projects/mizzou-news-crawler/locations/us-central1-a/clusters/mizzou-cluster
