# Cloud Build configuration for building ONLY the processor service
# Usage: gcloud builds submit --config=cloudbuild-processor-only.yaml
# Note: Uses shared base image from Artifact Registry

substitutions:
  _BASE_IMAGE: us-central1-docker.pkg.dev/${PROJECT_ID}/mizzou-crawler/base:latest
  _REGISTRY: us-central1-docker.pkg.dev/${PROJECT_ID}/mizzou-crawler
  _RELEASE_VERSION: '1.3.1'

steps:
  # Warm build cache from the last pushed image (non-fatal if missing)
  - name: 'gcr.io/cloud-builders/docker'
    id: 'warm-cache'
    entrypoint: 'bash'
    args:
      - '-lc'
      - |
        docker pull ${_REGISTRY}/processor:latest || true
  # Build Processor (using shared base image)
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-processor'
    env:
      - 'DOCKER_BUILDKIT=1'
    args:
      - 'build'
      - '--build-arg'
      - 'BASE_IMAGE=${_BASE_IMAGE}'
      - '--build-arg'
      - 'BUILDKIT_INLINE_CACHE=1'
      - '--cache-from'
      - '${_REGISTRY}/processor:latest'
      - '-t'
      - '${_REGISTRY}/processor:${SHORT_SHA}'
      - '-t'
      - '${_REGISTRY}/processor:latest'
      - '-t'
      - '${_REGISTRY}/processor:v${_RELEASE_VERSION}'
      - '-f'
      - 'Dockerfile.processor'
      - '.'

  # Push Processor
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-processor'
    args:
      - 'push'
      - '--all-tags'
      - '${_REGISTRY}/processor'
    waitFor: ['build-processor']

options:
  machineType: 'N1_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY

timeout: '300s'  # 5 minutes (reduced from 15 due to base image optimization)
