apiVersion: apps/v1
kind: Deployment
metadata:
  name: mizzou-processor
  namespace: ci-cd-lab
  labels:
    app: mizzou-processor
    component: processor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mizzou-processor
  template:
    metadata:
      labels:
        app: mizzou-processor
        component: processor
    spec:
      serviceAccountName: mizzou-app
      priorityClassName: service-standard
      containers:
      - name: processor
        image: processor
        imagePullPolicy: Always
        command:
          - python
          - orchestration/continuous_processor.py
        envFrom:
        - secretRef:
            name: origin-proxy-credentials
        env:
        - name: PYTHONPATH
          value: "/app:/opt/origin-shim"
        - name: DATABASE_ENGINE
          value: "postgresql+psycopg2"
        - name: DATABASE_HOST
          value: "127.0.0.1"
        - name: DATABASE_PORT
          value: "5432"
        - name: DATABASE_USER
          valueFrom:
            secretKeyRef:
              name: cloudsql-db-credentials
              key: username
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: cloudsql-db-credentials
              key: password
        - name: DATABASE_NAME
          valueFrom:
            secretKeyRef:
              name: cloudsql-db-credentials
              key: database
        - name: USE_CLOUD_SQL_CONNECTOR
          value: "true"
        - name: CLOUD_SQL_INSTANCE
          value: "mizzou-news-crawler:us-central1:mizzou-db-prod"
        - name: POLL_INTERVAL
          value: "60"
        - name: VERIFICATION_BATCH_SIZE
          value: "10"
        - name: EXTRACTION_BATCH_SIZE
          value: "20"
        - name: ANALYSIS_BATCH_SIZE
          value: "16"
        - name: GAZETTEER_BATCH_SIZE
          value: "50"
        - name: CAPTCHA_BACKOFF_BASE
          value: "2400"
        - name: CAPTCHA_BACKOFF_MAX
          value: "7200"
        - name: INTER_REQUEST_MIN
          value: "15.0"
        - name: INTER_REQUEST_MAX
          value: "25.0"
        - name: BATCH_SLEEP_SECONDS
          value: "60.0"
        - name: UA_ROTATE_BASE
          value: "4"
        - name: UA_ROTATE_JITTER
          value: "0.25"
        - name: DECODO_ROTATE_IP
          value: "true"
        - name: PROXY_PROVIDER
          value: "decodo"
        - name: USE_ORIGIN_PROXY
          value: "false"
        - name: SELENIUM_PROXY
          valueFrom:
            secretKeyRef:
              name: origin-proxy-credentials
              key: selenium-proxy-url
        - name: NO_PROXY
          value: "localhost,127.0.0.1,metadata.google.internal,huggingface.co,*.huggingface.co,cdn-lfs.huggingface.co,cdn.huggingface.co"
        - name: no_proxy
          value: "localhost,127.0.0.1,metadata.google.internal,huggingface.co,*.huggingface.co,cdn-lfs.huggingface.co,cdn.huggingface.co"
        resources:
          requests:
            cpu: 50m
            memory: 256Mi
          limits:
            cpu: 250m
            memory: 512Mi
        livenessProbe:
          exec:
            command:
              - /bin/sh
              - -c
              - "pgrep -f 'continuous_processor.py' > /dev/null"
          initialDelaySeconds: 30
          periodSeconds: 60
          timeoutSeconds: 5
          failureThreshold: 5
        readinessProbe:
          exec:
            command:
              - /bin/sh
              - -c
              - "pgrep -f 'continuous_processor.py' > /dev/null"
          initialDelaySeconds: 10
          periodSeconds: 30
          timeoutSeconds: 3
          failureThreshold: 3
