apiVersion: apps/v1
kind: Deployment
metadata:
  name: mizzou-api
  namespace: production
  labels:
    app: mizzou-api
    component: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mizzou-api
  template:
    metadata:
      labels:
        app: mizzou-api
        component: backend
    spec:
      serviceAccountName: mizzou-app
      containers:
      # Main API container
      - name: api
        image: us-central1-docker.pkg.dev/mizzou-news-crawler/mizzou-crawler/api:latest
        ports:
        - containerPort: 8000
          name: http
        env:
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: cloudsql-db-credentials
              key: username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: cloudsql-db-credentials
              key: password
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: cloudsql-db-credentials
              key: database
        - name: DATABASE_URL
          value: "postgresql://$(DB_USER):$(DB_PASSWORD)@127.0.0.1:5432/$(DB_NAME)"
        - name: PORT
          value: "8000"
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
      
      # Cloud SQL Proxy sidecar
      - name: cloud-sql-proxy
        image: gcr.io/cloud-sql-connectors/cloud-sql-proxy:2.14.2
        args:
          - "--structured-logs"
          - "--port=5432"
          - "mizzou-news-crawler:us-central1:mizzou-db-prod"
        securityContext:
          runAsNonRoot: true
          allowPrivilegeEscalation: false
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: mizzou-api
  namespace: production
  labels:
    app: mizzou-api
spec:
  type: LoadBalancer
  selector:
    app: mizzou-api
  ports:
  - port: 80
    targetPort: 8000
    protocol: TCP
    name: http
