apiVersion: batch/v1
kind: CronJob
metadata:
  name: mizzou-crawler
  namespace: production
  labels:
    app: mizzou-crawler
    component: crawler
spec:
  # Run daily at 2 AM UTC (adjust as needed)
  schedule: "0 2 * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: mizzou-crawler
            component: crawler
        spec:
          serviceAccountName: mizzou-app
          restartPolicy: OnFailure
          volumes:
          - name: origin-sitecustomize
            configMap:
              name: origin-sitecustomize
              items:
              - key: sitecustomize.py
                path: sitecustomize.py
          containers:
          # Main crawler container
          - name: crawler
            image: crawler
            volumeMounts:
            - name: origin-sitecustomize
              mountPath: /usr/local/lib/python3.12/site-packages/sitecustomize.py
              subPath: sitecustomize.py
            env:
            # Proxy configuration
            - name: USE_ORIGIN_PROXY
              value: "true"
            - name: ORIGIN_PROXY_URL
              valueFrom:
                secretKeyRef:
                  name: origin-proxy-credentials
                  key: ORIGIN_PROXY_URL
                  optional: true
            - name: PROXY_USERNAME
              valueFrom:
                secretKeyRef:
                  name: origin-proxy-credentials
                  key: PROXY_USERNAME
                  optional: true
            - name: PROXY_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: origin-proxy-credentials
                  key: PROXY_PASSWORD
                  optional: true
            - name: SELENIUM_PROXY
              valueFrom:
                secretKeyRef:
                  name: origin-proxy-credentials
                  key: SELENIUM_PROXY
                  optional: true
            # Cloud SQL Connector configuration (no proxy sidecar needed)
            - name: USE_CLOUD_SQL_CONNECTOR
              value: "true"
            - name: CLOUD_SQL_INSTANCE
              value: "mizzou-news-crawler:us-central1:mizzou-db-prod"
            - name: DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: cloudsql-db-credentials
                  key: username
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: cloudsql-db-credentials
                  key: password
            - name: DATABASE_NAME
              valueFrom:
                secretKeyRef:
                  name: cloudsql-db-credentials
                  key: database
            resources:
              requests:
                cpu: 500m
                memory: 1Gi
              limits:
                cpu: 1000m
                memory: 2Gi
