apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Namespace for all resources
namespace: production

# Resources to include
resources:
  - processor-deployment.yaml
  - api-deployment.yaml
  - crawler-cronjob.yaml
  - cli-deployment.yaml
  - pdbs/mizzou-api-pdb.yaml
  - pdbs/mizzou-processor-pdb.yaml

# Image substitution - Cloud Deploy will override these with --images flag
images:
  - name: processor
    newName: us-central1-docker.pkg.dev/mizzou-news-crawler/mizzou-crawler/processor
    newTag: latest
  - name: api
    newName: us-central1-docker.pkg.dev/mizzou-news-crawler/mizzou-crawler/api
    newTag: latest
  - name: crawler
    newName: us-central1-docker.pkg.dev/mizzou-news-crawler/mizzou-crawler/crawler
    newTag: latest
