apiVersion: batch/v1
kind: Job
metadata:
  name: lehigh-extraction
  namespace: production
spec:
  ttlSecondsAfterFinished: 86400  # Clean up after 24 hours
  template:
    metadata:
      labels:
        app: lehigh-extraction
    spec:
      serviceAccountName: mizzou-app
      restartPolicy: Never
      containers:
      - name: extraction
        image: us-central1-docker.pkg.dev/mizzou-news-crawler/mizzou-crawler/processor:916d972
        command:
          - python
          - -m
          - src.cli.cli_modular
          - extract
          - --dataset
          - Penn-State-Lehigh
          - --limit
          - "5"
          - --batches
          - "250"
        envFrom:
        - secretRef:
            name: origin-proxy-credentials
        env:
        # Database configuration
        - name: DATABASE_ENGINE
          value: "postgresql+psycopg2"
        - name: DATABASE_HOST
          value: "127.0.0.1"
        - name: DATABASE_PORT
          value: "5432"
        - name: DATABASE_USER
          valueFrom:
            secretKeyRef:
              name: cloudsql-db-credentials
              key: username
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: cloudsql-db-credentials
              key: password
        - name: DATABASE_NAME
          valueFrom:
            secretKeyRef:
              name: cloudsql-db-credentials
              key: database
        # Cloud SQL Connector
        - name: USE_CLOUD_SQL_CONNECTOR
          value: "true"
        - name: CLOUD_SQL_INSTANCE
          value: "mizzou-news-crawler:us-central1:mizzou-db-prod"
        # Proxy configuration
        - name: PROXY_PROVIDER
          value: "decodo"
        - name: USE_ORIGIN_PROXY
          value: "false"
        - name: SELENIUM_PROXY
          valueFrom:
            secretKeyRef:
              name: origin-proxy-credentials
              key: selenium-proxy-url
        # Aggressive rate limiting settings
        - name: INTER_REQUEST_MIN
          value: "15.0"
        - name: INTER_REQUEST_MAX
          value: "25.0"
        - name: CAPTCHA_BACKOFF_BASE
          value: "2400"
        - name: CAPTCHA_BACKOFF_MAX
          value: "7200"
        - name: BATCH_SLEEP_SECONDS
          value: "60.0"
        # User agent rotation (rotate every 3-5 requests)
        - name: UA_ROTATE_BASE
          value: "4"
        - name: UA_ROTATE_JITTER
          value: "0.25"
        # Decodo IP rotation (enabled by default)
        - name: DECODO_ROTATE_IP
          value: "true"
        # Bypass proxy for internal services
        - name: NO_PROXY
          value: "localhost,127.0.0.1,metadata.google.internal,huggingface.co,*.huggingface.co"
        resources:
          requests:
            cpu: 250m
            memory: 1Gi
          limits:
            cpu: 1000m
            memory: 3Gi
