apiVersion: batch/v1
kind: CronJob
metadata:
  name: mizzou-processor
  namespace: production
  labels:
    app: mizzou-processor
    component: processor
spec:
  # Run every 6 hours (adjust as needed)
  schedule: "0 */6 * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: mizzou-processor
            component: processor
        spec:
          serviceAccountName: mizzou-app
          restartPolicy: OnFailure
          containers:
          # Main processor container
          - name: processor
            image: us-central1-docker.pkg.dev/mizzou-news-crawler/mizzou-crawler/processor:latest
            env:
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: cloudsql-db-credentials
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: cloudsql-db-credentials
                  key: password
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: cloudsql-db-credentials
                  key: database
            - name: DATABASE_URL
              value: "postgresql://$(DB_USER):$(DB_PASSWORD)@127.0.0.1:5432/$(DB_NAME)"
            resources:
              requests:
                cpu: 500m
                memory: 1Gi
              limits:
                cpu: 1000m
                memory: 2Gi
          
          # Cloud SQL Proxy sidecar
          - name: cloud-sql-proxy
            image: gcr.io/cloud-sql-connectors/cloud-sql-proxy:2.14.2
            args:
              - "--structured-logs"
              - "--port=5432"
              - "mizzou-news-crawler:us-central1:mizzou-db-prod"
            securityContext:
              runAsNonRoot: true
              allowPrivilegeEscalation: false
            resources:
              requests:
                cpu: 100m
                memory: 128Mi
              limits:
                cpu: 200m
                memory: 256Mi
