"""Add API backend and telemetry tables

Revision ID: e3114395bcc4
Revises: 
Create Date: 2025-10-04 21:50:46.449816

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3114395bcc4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('background_processes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('process_type', sa.String(), nullable=False),
    sa.Column('command', sa.String(), nullable=False),
    sa.Column('pid', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('progress_current', sa.Integer(), nullable=True),
    sa.Column('progress_total', sa.Integer(), nullable=True),
    sa.Column('progress_message', sa.String(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('result_summary', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('dataset_id', sa.String(), nullable=True),
    sa.Column('source_id', sa.String(), nullable=True),
    sa.Column('process_metadata', sa.JSON(), nullable=True),
    sa.Column('parent_process_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['parent_process_id'], ['background_processes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_background_processes_dataset_id'), 'background_processes', ['dataset_id'], unique=False)
    op.create_index(op.f('ix_background_processes_pid'), 'background_processes', ['pid'], unique=False)
    op.create_index(op.f('ix_background_processes_process_type'), 'background_processes', ['process_type'], unique=False)
    op.create_index(op.f('ix_background_processes_source_id'), 'background_processes', ['source_id'], unique=False)
    op.create_index(op.f('ix_background_processes_status'), 'background_processes', ['status'], unique=False)
    op.create_table('byline_cleaning_telemetry',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('article_id', sa.String(), nullable=True),
    sa.Column('candidate_link_id', sa.String(), nullable=True),
    sa.Column('source_id', sa.String(), nullable=True),
    sa.Column('source_name', sa.String(), nullable=True),
    sa.Column('raw_byline', sa.Text(), nullable=True),
    sa.Column('raw_byline_length', sa.Integer(), nullable=True),
    sa.Column('raw_byline_words', sa.Integer(), nullable=True),
    sa.Column('extraction_timestamp', sa.DateTime(), nullable=False),
    sa.Column('cleaning_method', sa.String(), nullable=True),
    sa.Column('source_canonical_name', sa.String(), nullable=True),
    sa.Column('final_authors_json', sa.Text(), nullable=True),
    sa.Column('final_authors_count', sa.Integer(), nullable=True),
    sa.Column('final_authors_display', sa.String(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('processing_time_ms', sa.Float(), nullable=True),
    sa.Column('has_wire_service', sa.Boolean(), nullable=True),
    sa.Column('has_email', sa.Boolean(), nullable=True),
    sa.Column('has_title', sa.Boolean(), nullable=True),
    sa.Column('has_organization', sa.Boolean(), nullable=True),
    sa.Column('source_name_removed', sa.Boolean(), nullable=True),
    sa.Column('duplicates_removed_count', sa.Integer(), nullable=True),
    sa.Column('likely_valid_authors', sa.Boolean(), nullable=True),
    sa.Column('likely_noise', sa.Boolean(), nullable=True),
    sa.Column('requires_manual_review', sa.Boolean(), nullable=True),
    sa.Column('cleaning_errors', sa.Text(), nullable=True),
    sa.Column('parsing_warnings', sa.Text(), nullable=True),
    sa.Column('human_label', sa.String(), nullable=True),
    sa.Column('human_notes', sa.Text(), nullable=True),
    sa.Column('reviewed_by', sa.String(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_byline_cleaning_telemetry_article_id'), 'byline_cleaning_telemetry', ['article_id'], unique=False)
    op.create_index(op.f('ix_byline_cleaning_telemetry_candidate_link_id'), 'byline_cleaning_telemetry', ['candidate_link_id'], unique=False)
    op.create_index(op.f('ix_byline_cleaning_telemetry_extraction_timestamp'), 'byline_cleaning_telemetry', ['extraction_timestamp'], unique=False)
    op.create_index(op.f('ix_byline_cleaning_telemetry_source_id'), 'byline_cleaning_telemetry', ['source_id'], unique=False)
    op.create_index(op.f('ix_byline_cleaning_telemetry_source_name'), 'byline_cleaning_telemetry', ['source_name'], unique=False)
    op.create_table('byline_transformation_steps',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('telemetry_id', sa.String(), nullable=False),
    sa.Column('step_number', sa.Integer(), nullable=True),
    sa.Column('step_name', sa.String(), nullable=True),
    sa.Column('input_text', sa.Text(), nullable=True),
    sa.Column('output_text', sa.Text(), nullable=True),
    sa.Column('transformation_type', sa.String(), nullable=True),
    sa.Column('removed_content', sa.Text(), nullable=True),
    sa.Column('added_content', sa.Text(), nullable=True),
    sa.Column('confidence_delta', sa.Float(), nullable=True),
    sa.Column('processing_time_ms', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_byline_transformation_steps_telemetry_id'), 'byline_transformation_steps', ['telemetry_id'], unique=False)
    op.create_table('candidate_links',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('discovered_at', sa.DateTime(), nullable=False),
    sa.Column('crawl_depth', sa.Integer(), nullable=True),
    sa.Column('discovered_by', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(), nullable=True),
    sa.Column('http_status', sa.Integer(), nullable=True),
    sa.Column('content_hash', sa.String(), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.Column('publish_date', sa.DateTime(), nullable=True),
    sa.Column('source_host_id', sa.String(), nullable=True),
    sa.Column('source_name', sa.String(), nullable=True),
    sa.Column('source_city', sa.String(), nullable=True),
    sa.Column('source_county', sa.String(), nullable=True),
    sa.Column('source_type', sa.String(), nullable=True),
    sa.Column('frequency', sa.String(), nullable=True),
    sa.Column('owner', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('zip_code', sa.String(), nullable=True),
    sa.Column('cached_geographic_entities', sa.String(), nullable=True),
    sa.Column('cached_institutions', sa.String(), nullable=True),
    sa.Column('cached_schools', sa.String(), nullable=True),
    sa.Column('cached_government', sa.String(), nullable=True),
    sa.Column('cached_healthcare', sa.String(), nullable=True),
    sa.Column('cached_businesses', sa.String(), nullable=True),
    sa.Column('cached_landmarks', sa.String(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.Column('articles_found', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('dataset_id', sa.String(), nullable=True),
    sa.Column('source_id', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url', name='uq_candidate_links_url')
    )
    op.create_index(op.f('ix_candidate_links_content_hash'), 'candidate_links', ['content_hash'], unique=False)
    op.create_index(op.f('ix_candidate_links_dataset_id'), 'candidate_links', ['dataset_id'], unique=False)
    op.create_index(op.f('ix_candidate_links_priority'), 'candidate_links', ['priority'], unique=False)
    op.create_index(op.f('ix_candidate_links_publish_date'), 'candidate_links', ['publish_date'], unique=False)
    op.create_index(op.f('ix_candidate_links_source_city'), 'candidate_links', ['source_city'], unique=False)
    op.create_index(op.f('ix_candidate_links_source_county'), 'candidate_links', ['source_county'], unique=False)
    op.create_index(op.f('ix_candidate_links_source_host_id'), 'candidate_links', ['source_host_id'], unique=False)
    op.create_index(op.f('ix_candidate_links_source_id'), 'candidate_links', ['source_id'], unique=False)
    op.create_index(op.f('ix_candidate_links_source_name'), 'candidate_links', ['source_name'], unique=False)
    op.create_index(op.f('ix_candidate_links_status'), 'candidate_links', ['status'], unique=False)
    op.create_index(op.f('ix_candidate_links_url'), 'candidate_links', ['url'], unique=True)
    op.create_table('candidates',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('snapshot_id', sa.String(), nullable=True),
    sa.Column('selector', sa.String(), nullable=False),
    sa.Column('field', sa.String(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('words', sa.Integer(), nullable=True),
    sa.Column('snippet', sa.Text(), nullable=True),
    sa.Column('alts', sa.Text(), nullable=True),
    sa.Column('accepted', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_candidates_snapshot_id'), 'candidates', ['snapshot_id'], unique=False)
    op.create_table('code_review_telemetry',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('review_id', sa.String(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('line_number', sa.Integer(), nullable=True),
    sa.Column('code_snippet', sa.Text(), nullable=True),
    sa.Column('issue_type', sa.String(), nullable=True),
    sa.Column('severity', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('suggested_fix', sa.Text(), nullable=True),
    sa.Column('reviewer', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('human_label', sa.String(), nullable=True),
    sa.Column('human_notes', sa.Text(), nullable=True),
    sa.Column('reviewed_by', sa.String(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_code_review_telemetry_review_id'), 'code_review_telemetry', ['review_id'], unique=True)
    op.create_table('datasets',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('ingested_at', sa.DateTime(), nullable=False),
    sa.Column('ingested_by', sa.String(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_datasets_label'), 'datasets', ['label'], unique=True)
    op.create_index(op.f('ix_datasets_slug'), 'datasets', ['slug'], unique=True)
    op.create_table('dedupe_audit',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('article_uid', sa.String(), nullable=True),
    sa.Column('neighbor_uid', sa.String(), nullable=True),
    sa.Column('host', sa.String(), nullable=True),
    sa.Column('similarity', sa.Float(), nullable=True),
    sa.Column('dedupe_flag', sa.Boolean(), nullable=True),
    sa.Column('category', sa.Integer(), nullable=True),
    sa.Column('stage', sa.String(), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dedupe_audit_article_uid'), 'dedupe_audit', ['article_uid'], unique=False)
    op.create_index(op.f('ix_dedupe_audit_host'), 'dedupe_audit', ['host'], unique=False)
    op.create_table('domain_feedback',
    sa.Column('host', sa.String(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('host')
    )
    op.create_table('geocode_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('input', sa.Text(), nullable=False),
    sa.Column('normalized_input', sa.String(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lon', sa.Float(), nullable=True),
    sa.Column('precision', sa.String(), nullable=True),
    sa.Column('raw_response', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('attempt_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'normalized_input', name='uq_geocode_provider_norm')
    )
    op.create_index(op.f('ix_geocode_cache_normalized_input'), 'geocode_cache', ['normalized_input'], unique=False)
    op.create_index(op.f('ix_geocode_cache_provider'), 'geocode_cache', ['provider'], unique=False)
    op.create_table('jobs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('job_type', sa.String(), nullable=False),
    sa.Column('job_name', sa.String(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('exit_status', sa.String(), nullable=True),
    sa.Column('params', sa.JSON(), nullable=True),
    sa.Column('commit_sha', sa.String(), nullable=True),
    sa.Column('environment', sa.JSON(), nullable=True),
    sa.Column('artifact_paths', sa.JSON(), nullable=True),
    sa.Column('logs_path', sa.String(), nullable=True),
    sa.Column('records_processed', sa.Integer(), nullable=True),
    sa.Column('records_created', sa.Integer(), nullable=True),
    sa.Column('records_updated', sa.Integer(), nullable=True),
    sa.Column('errors_count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reextract_jobs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('host', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('result_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reextract_jobs_host'), 'reextract_jobs', ['host'], unique=False)
    op.create_index(op.f('ix_reextract_jobs_status'), 'reextract_jobs', ['status'], unique=False)
    op.create_table('reviews',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('article_idx', sa.Integer(), nullable=True),
    sa.Column('article_uid', sa.String(), nullable=True),
    sa.Column('reviewer', sa.String(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('secondary_rating', sa.Integer(), nullable=True),
    sa.Column('tags', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('mentioned_locations', sa.Text(), nullable=True),
    sa.Column('missing_locations', sa.Text(), nullable=True),
    sa.Column('incorrect_locations', sa.Text(), nullable=True),
    sa.Column('inferred_tags', sa.Text(), nullable=True),
    sa.Column('missing_tags', sa.Text(), nullable=True),
    sa.Column('incorrect_tags', sa.Text(), nullable=True),
    sa.Column('body_errors', sa.Text(), nullable=True),
    sa.Column('headline_errors', sa.Text(), nullable=True),
    sa.Column('author_errors', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reviews_article_idx'), 'reviews', ['article_idx'], unique=False)
    op.create_index(op.f('ix_reviews_article_uid'), 'reviews', ['article_uid'], unique=False)
    op.create_index(op.f('ix_reviews_reviewer'), 'reviews', ['reviewer'], unique=False)
    op.create_table('snapshots',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('host', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('path', sa.String(), nullable=True),
    sa.Column('pipeline_run_id', sa.String(), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('parsed_fields', sa.Text(), nullable=True),
    sa.Column('model_confidence', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_snapshots_host'), 'snapshots', ['host'], unique=False)
    op.create_index(op.f('ix_snapshots_pipeline_run_id'), 'snapshots', ['pipeline_run_id'], unique=False)
    op.create_index(op.f('ix_snapshots_status'), 'snapshots', ['status'], unique=False)
    op.create_table('sources',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('host', sa.String(), nullable=False),
    sa.Column('host_norm', sa.String(), nullable=False),
    sa.Column('canonical_name', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('county', sa.String(), nullable=True),
    sa.Column('owner', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sources_canonical_name'), 'sources', ['canonical_name'], unique=False)
    op.create_index(op.f('ix_sources_city'), 'sources', ['city'], unique=False)
    op.create_index(op.f('ix_sources_county'), 'sources', ['county'], unique=False)
    op.create_index(op.f('ix_sources_host'), 'sources', ['host'], unique=False)
    op.create_index(op.f('ix_sources_host_norm'), 'sources', ['host_norm'], unique=True)
    op.create_table('verification_jobs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('job_name', sa.String(), nullable=False),
    sa.Column('discovery_job_id', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('total_urls', sa.Integer(), nullable=True),
    sa.Column('processed_urls', sa.Integer(), nullable=True),
    sa.Column('verified_articles', sa.Integer(), nullable=True),
    sa.Column('verified_non_articles', sa.Integer(), nullable=True),
    sa.Column('verification_errors', sa.Integer(), nullable=True),
    sa.Column('avg_verification_time_ms', sa.Float(), nullable=True),
    sa.Column('total_processing_time_seconds', sa.Float(), nullable=True),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_verification_jobs_discovery_job_id'), 'verification_jobs', ['discovery_job_id'], unique=False)
    op.create_table('verification_patterns',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('pattern_type', sa.String(), nullable=False),
    sa.Column('pattern_regex', sa.String(), nullable=True),
    sa.Column('pattern_description', sa.String(), nullable=True),
    sa.Column('total_matches', sa.Integer(), nullable=True),
    sa.Column('article_matches', sa.Integer(), nullable=True),
    sa.Column('non_article_matches', sa.Integer(), nullable=True),
    sa.Column('article_rate', sa.Float(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('example_urls', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_verification_patterns_pattern_type'), 'verification_patterns', ['pattern_type'], unique=False)
    op.create_table('articles',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('candidate_link_id', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('author', sa.String(), nullable=True),
    sa.Column('publish_date', sa.DateTime(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('text_hash', sa.String(), nullable=True),
    sa.Column('text_excerpt', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('wire', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('raw_gcs_path', sa.String(), nullable=True),
    sa.Column('extracted_at', sa.DateTime(), nullable=False),
    sa.Column('extraction_version', sa.String(), nullable=True),
    sa.Column('primary_label', sa.String(), nullable=True),
    sa.Column('primary_label_confidence', sa.Float(), nullable=True),
    sa.Column('alternate_label', sa.String(), nullable=True),
    sa.Column('alternate_label_confidence', sa.Float(), nullable=True),
    sa.Column('label_version', sa.String(), nullable=True),
    sa.Column('label_model_version', sa.String(), nullable=True),
    sa.Column('labels_updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['candidate_link_id'], ['candidate_links.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_articles_label_version'), 'articles', ['label_version'], unique=False)
    op.create_index(op.f('ix_articles_status'), 'articles', ['status'], unique=False)
    op.create_index(op.f('ix_articles_text_hash'), 'articles', ['text_hash'], unique=False)
    op.create_index(op.f('ix_articles_url'), 'articles', ['url'], unique=False)
    op.create_table('dataset_sources',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('dataset_id', sa.String(), nullable=False),
    sa.Column('source_id', sa.String(), nullable=False),
    sa.Column('legacy_host_id', sa.String(), nullable=True),
    sa.Column('legacy_meta', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dataset_id', 'legacy_host_id', name='uq_dataset_legacy_host'),
    sa.UniqueConstraint('dataset_id', 'source_id', name='uq_dataset_source')
    )
    op.create_index(op.f('ix_dataset_sources_dataset_id'), 'dataset_sources', ['dataset_id'], unique=False)
    op.create_index(op.f('ix_dataset_sources_legacy_host_id'), 'dataset_sources', ['legacy_host_id'], unique=False)
    op.create_index(op.f('ix_dataset_sources_source_id'), 'dataset_sources', ['source_id'], unique=False)
    op.create_table('gazetteer',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('dataset_id', sa.String(), nullable=True),
    sa.Column('dataset_label', sa.String(), nullable=True),
    sa.Column('source_id', sa.String(), nullable=True),
    sa.Column('data_id', sa.String(), nullable=True),
    sa.Column('host_id', sa.String(), nullable=True),
    sa.Column('osm_type', sa.String(), nullable=True),
    sa.Column('osm_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('name_norm', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lon', sa.Float(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('distance_miles', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id', 'dataset_id', 'osm_type', 'osm_id', name='uq_gazetteer_source_dataset_osm')
    )
    op.create_index(op.f('ix_gazetteer_category'), 'gazetteer', ['category'], unique=False)
    op.create_index(op.f('ix_gazetteer_data_id'), 'gazetteer', ['data_id'], unique=False)
    op.create_index(op.f('ix_gazetteer_dataset_id'), 'gazetteer', ['dataset_id'], unique=False)
    op.create_index(op.f('ix_gazetteer_dataset_label'), 'gazetteer', ['dataset_label'], unique=False)
    op.create_index(op.f('ix_gazetteer_host_id'), 'gazetteer', ['host_id'], unique=False)
    op.create_index(op.f('ix_gazetteer_lat'), 'gazetteer', ['lat'], unique=False)
    op.create_index(op.f('ix_gazetteer_lon'), 'gazetteer', ['lon'], unique=False)
    op.create_index(op.f('ix_gazetteer_name_norm'), 'gazetteer', ['name_norm'], unique=False)
    op.create_index(op.f('ix_gazetteer_osm_id'), 'gazetteer', ['osm_id'], unique=False)
    op.create_index(op.f('ix_gazetteer_osm_type'), 'gazetteer', ['osm_type'], unique=False)
    op.create_index(op.f('ix_gazetteer_source_id'), 'gazetteer', ['source_id'], unique=False)
    op.create_table('url_verifications',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('candidate_link_id', sa.String(), nullable=False),
    sa.Column('verification_job_id', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('storysniffer_result', sa.Boolean(), nullable=True),
    sa.Column('verification_confidence', sa.Float(), nullable=True),
    sa.Column('verified_at', sa.DateTime(), nullable=False),
    sa.Column('verification_time_ms', sa.Float(), nullable=True),
    sa.Column('previous_status', sa.String(), nullable=True),
    sa.Column('new_status', sa.String(), nullable=True),
    sa.Column('verification_error', sa.String(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.Column('article_headline', sa.String(), nullable=True),
    sa.Column('article_excerpt', sa.Text(), nullable=True),
    sa.Column('human_label', sa.String(), nullable=True),
    sa.Column('human_notes', sa.Text(), nullable=True),
    sa.Column('reviewed_by', sa.String(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['candidate_link_id'], ['candidate_links.id'], ),
    sa.ForeignKeyConstraint(['verification_job_id'], ['verification_jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_url_verifications_candidate_link_id'), 'url_verifications', ['candidate_link_id'], unique=False)
    op.create_index(op.f('ix_url_verifications_url'), 'url_verifications', ['url'], unique=False)
    op.create_index(op.f('ix_url_verifications_verification_job_id'), 'url_verifications', ['verification_job_id'], unique=False)
    op.create_table('verification_telemetry',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('verification_job_id', sa.String(), nullable=False),
    sa.Column('source_name', sa.String(), nullable=True),
    sa.Column('source_county', sa.String(), nullable=True),
    sa.Column('total_urls', sa.Integer(), nullable=True),
    sa.Column('verified_articles', sa.Integer(), nullable=True),
    sa.Column('verified_non_articles', sa.Integer(), nullable=True),
    sa.Column('verification_errors', sa.Integer(), nullable=True),
    sa.Column('article_rate', sa.Float(), nullable=True),
    sa.Column('avg_verification_time_ms', sa.Float(), nullable=True),
    sa.Column('top_non_article_patterns', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['verification_job_id'], ['verification_jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_verification_telemetry_source_county'), 'verification_telemetry', ['source_county'], unique=False)
    op.create_index(op.f('ix_verification_telemetry_source_name'), 'verification_telemetry', ['source_name'], unique=False)
    op.create_index(op.f('ix_verification_telemetry_verification_job_id'), 'verification_telemetry', ['verification_job_id'], unique=False)
    op.create_table('article_entities',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('article_id', sa.String(), nullable=False),
    sa.Column('article_text_hash', sa.String(), nullable=True),
    sa.Column('entity_text', sa.String(), nullable=False),
    sa.Column('entity_norm', sa.String(), nullable=True),
    sa.Column('entity_label', sa.String(), nullable=True),
    sa.Column('osm_category', sa.String(), nullable=True),
    sa.Column('osm_subcategory', sa.String(), nullable=True),
    sa.Column('extractor_version', sa.String(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('matched_gazetteer_id', sa.String(), nullable=True),
    sa.Column('match_score', sa.Float(), nullable=True),
    sa.Column('match_name', sa.String(), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ),
    sa.ForeignKeyConstraint(['matched_gazetteer_id'], ['gazetteer.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('article_id', 'entity_norm', 'entity_label', 'extractor_version', name='uq_article_entity')
    )
    op.create_index(op.f('ix_article_entities_article_id'), 'article_entities', ['article_id'], unique=False)
    op.create_index(op.f('ix_article_entities_article_text_hash'), 'article_entities', ['article_text_hash'], unique=False)
    op.create_index(op.f('ix_article_entities_entity_label'), 'article_entities', ['entity_label'], unique=False)
    op.create_index(op.f('ix_article_entities_entity_norm'), 'article_entities', ['entity_norm'], unique=False)
    op.create_index(op.f('ix_article_entities_extractor_version'), 'article_entities', ['extractor_version'], unique=False)
    op.create_index(op.f('ix_article_entities_matched_gazetteer_id'), 'article_entities', ['matched_gazetteer_id'], unique=False)
    op.create_index(op.f('ix_article_entities_osm_category'), 'article_entities', ['osm_category'], unique=False)
    op.create_table('article_labels',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('article_id', sa.String(), nullable=False),
    sa.Column('label_version', sa.String(), nullable=False),
    sa.Column('model_version', sa.String(), nullable=False),
    sa.Column('model_path', sa.String(), nullable=True),
    sa.Column('primary_label', sa.String(), nullable=False),
    sa.Column('primary_label_confidence', sa.Float(), nullable=True),
    sa.Column('alternate_label', sa.String(), nullable=True),
    sa.Column('alternate_label_confidence', sa.Float(), nullable=True),
    sa.Column('applied_at', sa.DateTime(), nullable=False),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('article_id', 'label_version', name='uq_article_label_version')
    )
    op.create_index(op.f('ix_article_labels_article_id'), 'article_labels', ['article_id'], unique=False)
    op.create_index(op.f('ix_article_labels_label_version'), 'article_labels', ['label_version'], unique=False)
    op.create_table('locations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('article_id', sa.String(), nullable=False),
    sa.Column('entity_text', sa.String(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('geocoded_lat', sa.Float(), nullable=True),
    sa.Column('geocoded_lon', sa.Float(), nullable=True),
    sa.Column('geocoded_place', sa.String(), nullable=True),
    sa.Column('geocoding_source', sa.String(), nullable=True),
    sa.Column('extracted_at', sa.DateTime(), nullable=False),
    sa.Column('ner_model_version', sa.String(), nullable=True),
    sa.Column('geocoding_version', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ml_results',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('article_id', sa.String(), nullable=False),
    sa.Column('model_version', sa.String(), nullable=False),
    sa.Column('model_type', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('run_at', sa.DateTime(), nullable=False),
    sa.Column('job_id', sa.String(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ml_results')
    op.drop_table('locations')
    op.drop_index(op.f('ix_article_labels_label_version'), table_name='article_labels')
    op.drop_index(op.f('ix_article_labels_article_id'), table_name='article_labels')
    op.drop_table('article_labels')
    op.drop_index(op.f('ix_article_entities_osm_category'), table_name='article_entities')
    op.drop_index(op.f('ix_article_entities_matched_gazetteer_id'), table_name='article_entities')
    op.drop_index(op.f('ix_article_entities_extractor_version'), table_name='article_entities')
    op.drop_index(op.f('ix_article_entities_entity_norm'), table_name='article_entities')
    op.drop_index(op.f('ix_article_entities_entity_label'), table_name='article_entities')
    op.drop_index(op.f('ix_article_entities_article_text_hash'), table_name='article_entities')
    op.drop_index(op.f('ix_article_entities_article_id'), table_name='article_entities')
    op.drop_table('article_entities')
    op.drop_index(op.f('ix_verification_telemetry_verification_job_id'), table_name='verification_telemetry')
    op.drop_index(op.f('ix_verification_telemetry_source_name'), table_name='verification_telemetry')
    op.drop_index(op.f('ix_verification_telemetry_source_county'), table_name='verification_telemetry')
    op.drop_table('verification_telemetry')
    op.drop_index(op.f('ix_url_verifications_verification_job_id'), table_name='url_verifications')
    op.drop_index(op.f('ix_url_verifications_url'), table_name='url_verifications')
    op.drop_index(op.f('ix_url_verifications_candidate_link_id'), table_name='url_verifications')
    op.drop_table('url_verifications')
    op.drop_index(op.f('ix_gazetteer_source_id'), table_name='gazetteer')
    op.drop_index(op.f('ix_gazetteer_osm_type'), table_name='gazetteer')
    op.drop_index(op.f('ix_gazetteer_osm_id'), table_name='gazetteer')
    op.drop_index(op.f('ix_gazetteer_name_norm'), table_name='gazetteer')
    op.drop_index(op.f('ix_gazetteer_lon'), table_name='gazetteer')
    op.drop_index(op.f('ix_gazetteer_lat'), table_name='gazetteer')
    op.drop_index(op.f('ix_gazetteer_host_id'), table_name='gazetteer')
    op.drop_index(op.f('ix_gazetteer_dataset_label'), table_name='gazetteer')
    op.drop_index(op.f('ix_gazetteer_dataset_id'), table_name='gazetteer')
    op.drop_index(op.f('ix_gazetteer_data_id'), table_name='gazetteer')
    op.drop_index(op.f('ix_gazetteer_category'), table_name='gazetteer')
    op.drop_table('gazetteer')
    op.drop_index(op.f('ix_dataset_sources_source_id'), table_name='dataset_sources')
    op.drop_index(op.f('ix_dataset_sources_legacy_host_id'), table_name='dataset_sources')
    op.drop_index(op.f('ix_dataset_sources_dataset_id'), table_name='dataset_sources')
    op.drop_table('dataset_sources')
    op.drop_index(op.f('ix_articles_url'), table_name='articles')
    op.drop_index(op.f('ix_articles_text_hash'), table_name='articles')
    op.drop_index(op.f('ix_articles_status'), table_name='articles')
    op.drop_index(op.f('ix_articles_label_version'), table_name='articles')
    op.drop_table('articles')
    op.drop_index(op.f('ix_verification_patterns_pattern_type'), table_name='verification_patterns')
    op.drop_table('verification_patterns')
    op.drop_index(op.f('ix_verification_jobs_discovery_job_id'), table_name='verification_jobs')
    op.drop_table('verification_jobs')
    op.drop_index(op.f('ix_sources_host_norm'), table_name='sources')
    op.drop_index(op.f('ix_sources_host'), table_name='sources')
    op.drop_index(op.f('ix_sources_county'), table_name='sources')
    op.drop_index(op.f('ix_sources_city'), table_name='sources')
    op.drop_index(op.f('ix_sources_canonical_name'), table_name='sources')
    op.drop_table('sources')
    op.drop_index(op.f('ix_snapshots_status'), table_name='snapshots')
    op.drop_index(op.f('ix_snapshots_pipeline_run_id'), table_name='snapshots')
    op.drop_index(op.f('ix_snapshots_host'), table_name='snapshots')
    op.drop_table('snapshots')
    op.drop_index(op.f('ix_reviews_reviewer'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_article_uid'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_article_idx'), table_name='reviews')
    op.drop_table('reviews')
    op.drop_index(op.f('ix_reextract_jobs_status'), table_name='reextract_jobs')
    op.drop_index(op.f('ix_reextract_jobs_host'), table_name='reextract_jobs')
    op.drop_table('reextract_jobs')
    op.drop_table('jobs')
    op.drop_index(op.f('ix_geocode_cache_provider'), table_name='geocode_cache')
    op.drop_index(op.f('ix_geocode_cache_normalized_input'), table_name='geocode_cache')
    op.drop_table('geocode_cache')
    op.drop_table('domain_feedback')
    op.drop_index(op.f('ix_dedupe_audit_host'), table_name='dedupe_audit')
    op.drop_index(op.f('ix_dedupe_audit_article_uid'), table_name='dedupe_audit')
    op.drop_table('dedupe_audit')
    op.drop_index(op.f('ix_datasets_slug'), table_name='datasets')
    op.drop_index(op.f('ix_datasets_label'), table_name='datasets')
    op.drop_table('datasets')
    op.drop_index(op.f('ix_code_review_telemetry_review_id'), table_name='code_review_telemetry')
    op.drop_table('code_review_telemetry')
    op.drop_index(op.f('ix_candidates_snapshot_id'), table_name='candidates')
    op.drop_table('candidates')
    op.drop_index(op.f('ix_candidate_links_url'), table_name='candidate_links')
    op.drop_index(op.f('ix_candidate_links_status'), table_name='candidate_links')
    op.drop_index(op.f('ix_candidate_links_source_name'), table_name='candidate_links')
    op.drop_index(op.f('ix_candidate_links_source_id'), table_name='candidate_links')
    op.drop_index(op.f('ix_candidate_links_source_host_id'), table_name='candidate_links')
    op.drop_index(op.f('ix_candidate_links_source_county'), table_name='candidate_links')
    op.drop_index(op.f('ix_candidate_links_source_city'), table_name='candidate_links')
    op.drop_index(op.f('ix_candidate_links_publish_date'), table_name='candidate_links')
    op.drop_index(op.f('ix_candidate_links_priority'), table_name='candidate_links')
    op.drop_index(op.f('ix_candidate_links_dataset_id'), table_name='candidate_links')
    op.drop_index(op.f('ix_candidate_links_content_hash'), table_name='candidate_links')
    op.drop_table('candidate_links')
    op.drop_index(op.f('ix_byline_transformation_steps_telemetry_id'), table_name='byline_transformation_steps')
    op.drop_table('byline_transformation_steps')
    op.drop_index(op.f('ix_byline_cleaning_telemetry_source_name'), table_name='byline_cleaning_telemetry')
    op.drop_index(op.f('ix_byline_cleaning_telemetry_source_id'), table_name='byline_cleaning_telemetry')
    op.drop_index(op.f('ix_byline_cleaning_telemetry_extraction_timestamp'), table_name='byline_cleaning_telemetry')
    op.drop_index(op.f('ix_byline_cleaning_telemetry_candidate_link_id'), table_name='byline_cleaning_telemetry')
    op.drop_index(op.f('ix_byline_cleaning_telemetry_article_id'), table_name='byline_cleaning_telemetry')
    op.drop_table('byline_cleaning_telemetry')
    op.drop_index(op.f('ix_background_processes_status'), table_name='background_processes')
    op.drop_index(op.f('ix_background_processes_source_id'), table_name='background_processes')
    op.drop_index(op.f('ix_background_processes_process_type'), table_name='background_processes')
    op.drop_index(op.f('ix_background_processes_pid'), table_name='background_processes')
    op.drop_index(op.f('ix_background_processes_dataset_id'), table_name='background_processes')
    op.drop_table('background_processes')
    # ### end Alembic commands ###
