# Cloud Build Trigger for ML Base Image
# This trigger should be run manually or when ML dependencies change
# Run infrequently since ML packages (torch, transformers) rarely update

name: build-ml-base-manual
description: Build ML base image with PyTorch, Transformers, and extraction tools
filename: gcp/cloudbuild/cloudbuild-ml-base.yaml

# Manual trigger - only run when ML dependencies change
github:
  owner: LocalNewsImpact
  name: MizzouNewsCrawler
  push:
    branch: ^feature/gcp-kubernetes-deployment$

# Only trigger on changes to ML-related files
includedFiles:
  - requirements-ml.txt
  - Dockerfile.ml-base
  - gcp/cloudbuild/cloudbuild-ml-base.yaml

substitutions:
  _BASE_IMAGE: us-central1-docker.pkg.dev/mizzou-news-crawler/mizzou-crawler/base:latest

tags:
  - ml-base
  - infrastructure
