# Kubernetes Job Manifest Template for Dataset Discovery
# 
# This template creates an isolated discovery job for a specific dataset.
# Discovery jobs find new article URLs from RSS feeds, sitemaps, and homepages.
#
# Placeholders to replace:
#   - DATASET_SLUG: Dataset identifier (e.g., "Penn-State-Lehigh", "Mizzou")
#   - PROCESSOR_IMAGE: Container image path
#   - SOURCE_LIMIT: Max sources to process (optional, default: process all)
#   - MAX_ARTICLES: Max articles per source (default: 50)
#   - DAYS_BACK: How many days to look back (default: 7)
#
# To apply: kubectl apply -f <your-customized-file.yaml>

apiVersion: batch/v1
kind: Job
metadata:
  labels:
    app: discover-dataset_slug
    dataset: DATASET_SLUG
    type: discovery
  name: discover-dataset_slug
  namespace: production
spec:
  template:
    metadata:
      labels:
        app: discover-dataset_slug
        dataset: DATASET_SLUG
        type: discovery
    spec:
      containers:
      - command:
        - python
        - -m
        - src.cli.cli_modular
        - discover-urls
        - --dataset
        - DATASET_SLUG
        - --max-articles
        - '50'
        - --days-back
        - '7'
        env:
        - name: DATABASE_ENGINE
          value: postgresql+psycopg2
        - name: DATABASE_HOST
          value: 127.0.0.1
        - name: DATABASE_PORT
          value: '5432'
        - name: DATABASE_USER
          valueFrom:
            secretKeyRef:
              key: username
              name: cloudsql-db-credentials
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: cloudsql-db-credentials
        - name: DATABASE_NAME
          valueFrom:
            secretKeyRef:
              key: database
              name: cloudsql-db-credentials
        - name: USE_CLOUD_SQL_CONNECTOR
          value: 'true'
        - name: CLOUD_SQL_INSTANCE
          value: mizzou-news-crawler:us-central1:mizzou-db-prod
        - name: PROXY_PROVIDER
          value: decodo
        - name: USE_ORIGIN_PROXY
          value: 'true'
        - name: SELENIUM_PROXY
          valueFrom:
            secretKeyRef:
              key: selenium-proxy-url
              name: origin-proxy-credentials
        - name: NO_PROXY
          value: localhost,127.0.0.1,metadata.google.internal,huggingface.co,*.huggingface.co
        envFrom:
        - secretRef:
            name: origin-proxy-credentials
        image: PROCESSOR_IMAGE
        name: discovery
        resources:
          limits:
            cpu: 500m
            memory: 2Gi
          requests:
            cpu: 100m
            memory: 768Mi
      restartPolicy: Never
      serviceAccountName: mizzou-app
      priorityClassName: batch-standard
  ttlSecondsAfterFinished: 86400

