substitutions:
  _BASE_IMAGE: us-central1-docker.pkg.dev/${PROJECT_ID}/mizzou-crawler/base:latest
  _REGISTRY: us-central1-docker.pkg.dev/${PROJECT_ID}/mizzou-crawler
  _RELEASE_VERSION: '1.3.1'

steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--build-arg'
      - 'BASE_IMAGE=${_BASE_IMAGE}'
      - '-f'
      - 'Dockerfile.crawler'
      - '-t'
      - '${_REGISTRY}/crawler:${SHORT_SHA}'
      - '-t'
      - '${_REGISTRY}/crawler:latest'
      - '-t'
      - '${_REGISTRY}/crawler:v${_RELEASE_VERSION}'
      - '.'
  # Get GKE credentials for kubectl commands
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'get-gke-credentials'
    args:
      - 'container'
      - 'clusters'
      - 'get-credentials'
      - 'mizzou-cluster'
      - '--zone=us-central1-a'

  # Update Argo WorkflowTemplate to use new crawler image SHA
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'update-argo-workflow-template'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        if [ "${BRANCH_NAME}" = "main" ]; then
          echo "🔄 Updating Argo WorkflowTemplate with crawler:${SHORT_SHA}..."
          bash gcp/cloudbuild/update-workflow-template.sh crawler "${SHORT_SHA}" "${_REGISTRY}"
        else
          echo "ℹ️  Skipping Argo WorkflowTemplate update - not on main branch (${BRANCH_NAME})"
        fi
    waitFor: ['get-gke-credentials']

images:
  - '${_REGISTRY}/crawler:${SHORT_SHA}'
  - '${_REGISTRY}/crawler:v${_RELEASE_VERSION}'
  - '${_REGISTRY}/crawler:latest'
timeout: 1800s
options:
  machineType: 'N1_HIGHCPU_8'
  diskSizeGb: 100
  logging: CLOUD_LOGGING_ONLY
  substitutionOption: 'ALLOW_LOOSE'
