name: CI

# CI workflow for MizzouNewsCrawler
#
# quick-checks-integration job: runs a focused Alembic/Postgres integration test
# (resync migration) against a PostgreSQL instance. This job is gated on the
# repository secret `TEST_DATABASE_URL` (CI-managed DB) to avoid accidental runs
# on forks or feature branches. It may also be manually dispatched on `main`.
# The job uses a service container (postgres:15) on GitHub-hosted runners, or
# can be triggered with TEST_DATABASE_URL env pointing to an external DB.

on:
  push:
    branches: 
      - main  # Only run CI on main branch
  pull_request:
    branches: 
      - main  # Only run CI on PRs to main branch
  schedule:
    # Run stress job weekly at 03:00 UTC on Sundays (example)
    - cron: '0 3 * * 0'
  workflow_dispatch: {}

jobs:
  lint:
    name: Lint & Format Check
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: 'requirements*.txt'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt

      - name: Run ruff
        run: python -m ruff check .

      - name: Check code formatting with black
        run: python -m black --check src/ tests/ web/

      - name: Check import sorting with isort
        run: python -m isort --check-only --profile black src/ tests/ web/

      - name: Run mypy type checker
        run: python -m mypy src/ --ignore-missing-imports
        continue-on-error: true  # Advisory only, matching local Makefile behavior

      - name: Validate deployment configurations
        run: |
          echo "Validating k8s deployment YAML..."
          
          # Verify PYTHONPATH includes /app
          if ! grep -q 'value: "/app:' k8s/processor-deployment.yaml; then
            echo "❌ PYTHONPATH does not include /app!"
            exit 1
          fi
          
          # Verify image is placeholder (not :latest)
          if grep -q 'image:.*:latest' k8s/processor-deployment.yaml; then
            echo "❌ Deployment uses image:latest!"
            exit 1
          fi
          
          echo "✅ Deployment YAML validation passed"

  mypy-strict:
    name: Mypy (strict on main)
    runs-on: ubuntu-latest
    needs: [lint]
    # Only run this job on direct pushes to main; PRs still run the advisory mypy in lint
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: 'requirements*.txt'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt

      - name: Run mypy (fail on errors)
        run: python -m mypy src/ --ignore-missing-imports

  security:
    name: Security Scan (weekly/manual only)
    runs-on: ubuntu-latest
    needs: [lint]
    if: github.event_name == 'schedule' || github.event_name == 'workflow_dispatch'
    
    steps:
      - uses: actions/checkout@v4


      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: 'requirements*.txt'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt

      - name: Run bandit security scan
        run: |
          python -m bandit -r src/ -ll -f txt || true
          echo "Bandit found issues but not failing build (review recommended)"

      - name: Check dependency vulnerabilities with safety
        run: |
          python -m safety check --json || true
          echo "Safety check completed (review recommended)"
        continue-on-error: true

  unit:
    name: Unit Tests (fast)
    runs-on: ubuntu-latest
    needs: [lint]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: 'pip'

      - name: Create data directory for tests
        run: mkdir -p data

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt

      - name: Run unit tests
        env:
          DATABASE_URL: "sqlite:///:memory:"
          TELEMETRY_DATABASE_URL: "sqlite:///:memory:"
        run: |
          python3 scripts/validate_workflow_templates.py
          pytest -q --override-ini="addopts=" -p no:pytest-cov tests/unit/test_argo_workflow_template.py tests/unit/test_verification_no_head.py

  quick-checks:
    name: Quick Workflow Template Checks (merge-to-main)
    runs-on: ubuntu-latest
    needs: [lint]
    # Run on direct pushes to main (merge-to-main) and on PRs targeting main
    if: |
      github.event_name == 'push' && github.ref == 'refs/heads/main'
      || github.event_name == 'pull_request' && github.base_ref == 'main'

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: 'requirements*.txt'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt

      - name: Create data directory for tests
        run: mkdir -p data

      - name: Quick validator and targeted tests
        env:
          TELEMETRY_DATABASE_URL: "sqlite:///:memory:"
          # Ensure targeted run doesn't pick up repo-level coverage addopts
          PYTEST_ADDOPTS: ""
        run: |
          # Validate Argo workflow templates and compile embedded scripts
          python3 scripts/validate_workflow_templates.py
          # Run the two targeted unit tests, ignore pytest.ini coverage and postgres plugins
          pytest -q -c /dev/null -p no:pytest_cov -p no:pytest_postgresql tests/unit/test_argo_workflow_template.py tests/unit/test_verification_no_head.py

  origin-proxy-only:
    name: Origin-proxy tests (smoke)
    runs-on: ubuntu-latest
    needs: [lint]  # Run early in parallel with unit tests
    # Only run smoke tests on main branch or PRs to main
    if: github.event_name == 'push' || github.base_ref == 'main' || github.ref == 'refs/heads/main'

    steps:
      - uses: actions/checkout@v4


      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: 'requirements*.txt'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt

      - name: Create data directory for tests
        run: mkdir -p data

      - name: Run origin-proxy tests only
        env:
          DATABASE_URL: "sqlite:///:memory:"
          TELEMETRY_DATABASE_URL: "sqlite:///:memory:"
          PYTEST_ADDOPTS: "-q --maxfail=1"
        run: |
          # Avoid repo-level coverage gating for the smoke run by overriding
          # addopts. The integration job still enforces coverage for the full run.
          pytest --override-ini addopts="" $PYTEST_ADDOPTS tests/test_origin_proxy.py tests/test_integration_proxy.py

  postgres-integration:
    name: PostgreSQL Integration Tests
    runs-on: ubuntu-latest
    needs: [unit]
    # Only run full integration tests on main branch or PRs to main
    if: github.event_name == 'push' || github.base_ref == 'main' || github.ref == 'refs/heads/main'

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: mizzou_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: 'requirements*.txt'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt

      - name: Create data directory for tests
        run: mkdir -p data

      - name: Run Alembic migrations on test database
        env:
          DATABASE_URL: "postgresql://postgres:postgres@localhost:5432/mizzou_test"
          DATABASE_ENGINE: "postgresql"
          DATABASE_HOST: "localhost"
          DATABASE_PORT: "5432"
          DATABASE_NAME: "mizzou_test"
          DATABASE_USER: "postgres"
          DATABASE_PASSWORD: "postgres"
        run: |
          alembic upgrade head

      - name: Run integration tests with PostgreSQL
        env:
          DATABASE_URL: "postgresql://postgres:postgres@localhost:5432/mizzou_test"
          TELEMETRY_DATABASE_URL: "postgresql://postgres:postgres@localhost:5432/mizzou_test"
          TEST_DATABASE_URL: "postgresql://postgres:postgres@localhost:5432/mizzou_test"
          DATABASE_ENGINE: "postgresql"
          DATABASE_HOST: "localhost"
          DATABASE_PORT: "5432"
          DATABASE_NAME: "mizzou_test"
          DATABASE_USER: "postgres"
          DATABASE_PASSWORD: "postgres"
        run: |
          # Run telemetry integration tests against PostgreSQL
          pytest -v -m "postgres" tests/test_telemetry_store_postgres.py tests/utils/test_byline_telemetry.py tests/utils/test_content_cleaning_telemetry.py || echo "Some PostgreSQL tests may not have postgres marker yet"

  integration:
    name: Integration & Coverage
    runs-on: ubuntu-latest
    needs: [unit]
    # Only run full integration tests on main branch or PRs to main
    if: github.event_name == 'push' || github.base_ref == 'main' || github.ref == 'refs/heads/main'

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: 'requirements*.txt'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt

      - name: Create data directory for tests
        run: mkdir -p data

      - name: Run full tests with coverage
        env:
          # Override database URL to use in-memory for faster tests
          DATABASE_URL: "sqlite:///:memory:"
          TELEMETRY_DATABASE_URL: "sqlite:///:memory:"
        run: pytest --cov=src --cov-report=xml --cov-report=html --cov-report=term-missing --cov-fail-under=78

      - name: Generate coverage summary
        if: success()
        run: python tools/generate_coverage_summary.py coverage.xml coverage-summary.md

  quick-checks-integration:
    name: Quick DB Integration (resync migration)
    runs-on: ubuntu-latest
    needs: [unit]
    # Only run on manual dispatch to main branch (requires TEST_DATABASE_URL secret)
    if: github.event_name == 'workflow_dispatch' && github.ref == 'refs/heads/main'

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: mizzou_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    env:
      TEST_DATABASE_URL: "${{ secrets.TEST_DATABASE_URL }}"

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: 'requirements*.txt'

      - name: Install dependencies
        env:
          PIP_CACHE_DIR: ~/.cache/pip
        run: |
          python -m pip install --upgrade pip
          pip install --cache-dir "$PIP_CACHE_DIR" -r requirements.txt
          pip install --cache-dir "$PIP_CACHE_DIR" -r requirements-dev.txt

      - name: Wait for Postgres
        run: |
          for i in {1..30}; do
            pg_isready -h localhost -p 5432 && break || sleep 1
          done

      - name: Run resync migration test (capture logs)
        env:
          # If TEST_DATABASE_URL secret is provided it overrides the local service
          TEST_DATABASE_URL: "${{ env.TEST_DATABASE_URL }}"
          DATABASE_URL: "postgresql://postgres:postgres@localhost:5432/mizzou_test"
          DATABASE_ENGINE: "postgresql"
          DATABASE_HOST: "localhost"
          DATABASE_PORT: "5432"
          DATABASE_NAME: "mizzou_test"
          DATABASE_USER: "postgres"
          DATABASE_PASSWORD: "postgres"
        run: |
          set -o pipefail
          mkdir -p ci-logs
          # Run the focused test and tee verbose output to a log file for upload on failure
          pytest -vv tests/alembic/test_resync_sequence_postgres.py -c /dev/null 2>&1 | tee ci-logs/resync-test.log

      - name: Upload logs on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: resync-test-logs
          path: ci-logs/
          if-no-files-found: warn

      - name: Upload coverage artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-py311
          path: |
            coverage.xml
            coverage-summary.md
            htmlcov/
          if-no-files-found: warn

  stress:
    name: Stress Concurrency Tests (scheduled/manual only)
    runs-on: ubuntu-latest
    if: github.event_name == 'schedule' || github.event_name == 'workflow_dispatch'
    steps:
      - uses: actions/checkout@v4


      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: 'requirements*.txt'

      - name: Install dependencies (includes extras for stress)
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt

      - name: Run stress tests with RUN_STRESS_TESTS=1
        env:
          DATABASE_URL: "sqlite:///:memory:"
          TELEMETRY_DATABASE_URL: "sqlite:///:memory:"
          RUN_STRESS_TESTS: '1'
        run: |
          pytest --override-ini addopts="-q" tests/test_versioning_concurrent_stress.py
