name: Smoke — Proxy adapter tests

on:
  pull_request:
    branches: [feature/gcp-kubernetes-deployment, main]
  workflow_dispatch: {}

jobs:
  smoke-proxy-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: Run proxy smoke tests
        env:
          PYTHONPATH: ${{ github.workspace }}
        run: |
          # Run only the two new proxy tests and bypass repo pytest.ini by
          # passing -c /dev/null so coverage gating doesn't force a full run.
          pytest -q -c /dev/null \
            tests/test_origin_proxy.py::test_enable_origin_proxy_rewrites_url_and_sets_auth \
            tests/test_integration_proxy.py::test_integration_origin_proxy
