name: Smoke — Proxy adapter tests

on:
  pull_request:
    branches: [feature/gcp-kubernetes-deployment, main]
  workflow_dispatch: {}

jobs:
  smoke-proxy-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: Run proxy smoke tests
        env:
          PYTHONPATH: ${{ github.workspace }}
          # Keep pytest quiet and fail fast; we run explicit files to avoid
          # collecting the entire test suite which would trigger coverage gating.
          PYTEST_ADDOPTS: "-q --maxfail=1"
        run: |
          # Run the targeted test files directly (no -c /dev/null bypass).
          # Run targeted files and explicitly override addopts so repo-level
          # coverage gating does not apply to this smoke job.
          pytest --override-ini addopts="" $PYTEST_ADDOPTS tests/test_origin_proxy.py tests/test_integration_proxy.py
